language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm
    
matrix:
    allow_failures:
        - php: hhvm

services:
    - mongodb
    - redis-server

before_script:
    - sh -c "type -p pecl"
    - sh -c 'php_ini=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; if [ -w "$php_ini" ]; then echo "extension = mongo.so" >> "$php_ini"; fi;'
    - sh -c 'if type -p pecl > /dev/null 2>&1; then pecl install redis; fi'
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres

script: phpunit -v
