language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

services:
    - mongodb
    - redis-server

before_script:
    - sh -c 'php_ini="~/.phpenv/versions/$(phpenv version-name)/etc/php.ini"; if [ -w $php_ini ]; then echo "extension = mongo.so" >> $php_ini; fi;'
    - pecl install redis
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres

script: phpunit -v
