language: php

php:
    - 5.4
    - 5.5
    - hhvm
    
matrix:
    allow_failures:
        - php: hhvm

services:
    - mongodb
    - redis-server

before_script:
    - sh -c 'if [ "hhvm" != $TRAVIS_PHP_VERSION ]; then printf "extension = mongo.so\nextension = redis.so" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini; fi;'
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres
    - composer install

script: phpunit -v
