language: php

php:
    - 5.3
    - 5.4
    - 5.5

services:
    - mongodb
    - redis-server

before_script:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - pecl install redis
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres

script: phpunit -v
