language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

services:
    - mongodb
    - redis-server

before_install:
    - wget http://tarantool.org/dist/public.key && sudo apt-key add ./public.key && release=`lsb_release -c -s` && echo "deb http://tarantool.org/dist/stable/ubuntu/ $release main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list && echo "deb-src http://tarantool.org/dist/stable/ubuntu/ $release main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get update

install:
    - sudo apt-get install tarantool tarantool-client
    - sudo wget https://raw.githubusercontent.com/tarantool/queue/master/init.lua -O /usr/share/tarantool/lua/init.lua
    - sudo wget https://raw.githubusercontent.com/tarantool/queue/master/tarantool.cfg -O /etc/tarantool/instances.enabled/queue.cfg
    - sudo service tarantool restart
    #- git clone https://github.com/tarantool/tarantool-php.git && cd ./tarantool-php && phpize && ./configure && make && sudo make install
    - git clone https://github.com/tony2001/tarantool-php.git && cd ./tarantool-php && phpize && ./configure && make && sudo make install

    - sudo apt-get install -y beanstalkd
    - sudo beanstalkd -d -l 127.0.0.1 -p 11300

    - bash -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then printf "extension = mongo.so\nextension = redis.so\nextension = tarantool.so" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini; fi;'

before_script:
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres
    - composer require phpunit/phpunit:~4.0
    - bash -c 'if [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then composer require mongofill/mongofill:dev-master; fi;'
    - composer install

script: phpunit -v
