language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

services:
    - mongodb
    - redis-server

install:
    - sudo apt-get install -y beanstalkd
    - sudo beanstalkd -d -l 127.0.0.1 -p 11300
    - sh -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then printf "extension = mongo.so\nextension = redis.so" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini; fi;'

before_script:
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres
    - composer require phpunit/phpunit:~4.0
    - composer install

script: phpunit -v
