language: php

php:
    - 5.3
    - 5.4

before_script:
    - ./tests/install_deps.sh
    - mysql -e 'create database phive_tests;'
    - psql -c 'create database phive_tests;' -U postgres

script: phpunit -v --exclude-group extra
